# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='uemail',
        ),
    ]
