# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20161030_0311'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='point_one',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='point_two',
        ),
        migrations.AddField(
            model_name='friendship',
            name='from_friend',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to='login_reg_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='to_friend',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_friend_set', to='login_reg_app.User'),
            preserve_default=False,
        ),
    ]
